"""init

Revision ID: f3e688e25279
Revises: 
Create Date: 2026-07-03 15:51:20.271226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e688e25279'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_admin_single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('cookies',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('original_format', sa.Text(), nullable=False),
    sa.Column('encrypted_content', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("original_format IN ('txt','json')", name='ck_cookies_original_format'),
    sa.CheckConstraint("status IN ('valid','unverified','invalid','expired')", name='ck_cookies_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_events_created_at', ['created_at'], unique=False)

    op.create_table('monitored_accounts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('tiktok_username', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('capture_mode', sa.Text(), nullable=False),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.Column('last_video_timestamp', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('avatar_local_path', sa.Text(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('total_likes', sa.Integer(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('profile_last_refreshed', sa.DateTime(), nullable=True),
    sa.Column('backfill_status', sa.Text(), nullable=False),
    sa.Column('backfill_cursor', sa.Text(), nullable=True),
    sa.Column('backfill_total', sa.Integer(), nullable=True),
    sa.Column('backfill_done', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("backfill_status IN ('idle','backfilling','paused','completed','cancelled')", name='ck_monitored_accounts_backfill_status'),
    sa.CheckConstraint("capture_mode IN ('history_and_monitor','monitor_only')", name='ck_monitored_accounts_capture_mode'),
    sa.CheckConstraint("status IN ('ok','needs_review','paused')", name='ck_monitored_accounts_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tiktok_username')
    )
    op.create_table('videos',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('monitored_account_id', sa.Text(), nullable=False),
    sa.Column('tiktok_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('upload_date', sa.Text(), nullable=True),
    sa.Column('upload_timestamp', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('error_kind', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("error_kind IN ('auth','rate_limit','ip_block','network','not_found','unknown')", name='ck_videos_error_kind'),
    sa.CheckConstraint("status IN ('queued','downloading','downloaded','failed')", name='ck_videos_status'),
    sa.ForeignKeyConstraint(['monitored_account_id'], ['monitored_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tiktok_id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index('idx_videos_account_id', ['monitored_account_id'], unique=False)
        batch_op.create_index('idx_videos_downloaded_at', ['downloaded_at'], unique=False)
        batch_op.create_index('idx_videos_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index('idx_videos_status')
        batch_op.drop_index('idx_videos_downloaded_at')
        batch_op.drop_index('idx_videos_account_id')

    op.drop_table('videos')
    op.drop_table('monitored_accounts')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('idx_events_created_at')

    op.drop_table('events')
    op.drop_table('cookies')
    op.drop_table('app_settings')
    op.drop_table('admin')
    # ### end Alembic commands ###
